[package]
name = "rust-opengl-test"
version = "0.2.0"
authors = [ "jhasse@bixense.com" ]
edition = "2021"

[[bin]]
name = "rust-opengl-test"

[dependencies]
log = "0.4"
time = "0.3"
gl = "0.14"
glutin = "0.19"
freetype-rs = "0.26"
nalgebra = "0.32"
